# -*- mode: ruby -*-
# vi: set ft=ruby :
VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
# Se crea la máquina virtual con el servicio de database con los recipes del mirror y mysql
config.vm.define :centos_database do |node|
 	node.vm.box = "centos64"
	node.vm.network :private_network, ip: "192.168.56.102"
	node.vm.network "public_network", :bridge => "eth3", ip:"192.168.131.22", :auto_config =>  		"false", :netmask => "255.255.255.0"
	 node.vm.provider :virtualbox do |vb|
		vb.customize ["modifyvm", :id, "--memory", "1024","--cpus", "4", "--name", 	      		"centos_databaseprueba" ]
	 end
	 config.vm.provision :chef_solo do |chef|
	  chef.cookbooks_path = "cookbooks"
	  chef.add_recipe "mirror"
	  chef.add_recipe "mysql"
	  chef.json = {"aptmirror" => {"server" => "192.168.131.254"}}
	 end
    end

# Se crea la máquina virtual con el servicio de Node.js con los recipes del mirror y node
   config.vm.define :centos_node do |node|
 	node.vm.box = "centos64"
	node.vm.network :private_network, ip: "192.168.56.101"
	node.vm.network "public_network", :bridge => "eth3", ip:"192.168.131.21", :auto_config => 		"false", :netmask => "255.255.255.0"
	 node.vm.provider :virtualbox do |vb|
		vb.customize ["modifyvm", :id, "--memory", "1024","--cpus", "4", "--name", "centos_nodeprueba" ]
	 end
	 config.vm.provision :chef_solo do |chef|
		      	chef.cookbooks_path = "cookbooks"
		      	chef.add_recipe "mirror"
			chef.add_recipe "node"
		      	chef.json = {"aptmirror" => {"server" => "192.168.131.254"}}
	 end
    end
    
    
end

